import { Product, ColdStorageUnit, DeliveryPartner, SupportTicket, Order } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'p1',
    name: 'DairyFresh Standard Cow Milk',
    category: 'Cow Milk',
    price: 33,
    unit: '500 ml',
    stock: 240,
    fatPercentage: 3.8,
    snfPercentage: 8.5,
    farmName: 'Green Valley Organic Farms',
    milkingTime: '04:30 AM',
    processingTime: '06:00 AM',
    dispatchTime: '07:15 AM',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=600',
    description: 'Freshly milked, pasteurized cow milk with standard fat content. Perfect for daily tea, coffee, and growing kids.',
    ingredients: 'Pasteurized Cow Milk with Vitamin A & D fortification',
    nutrition: {
      calories: '61 kcal',
      protein: '3.2g',
      fat: '3.8g',
      carbs: '4.7g',
      calcium: '120mg'
    },
    shelfLife: '48 Hours from packing',
    storageInstructions: 'Keep refrigerated under 4°C at all times.',
    rating: 4.8,
    reviewsCount: 142,
    isPopular: true,
  },
  {
    id: 'p2',
    name: 'DairyFresh Creamy Buffalo Milk',
    category: 'Buffalo Milk',
    price: 45,
    unit: '500 ml',
    stock: 180,
    fatPercentage: 6.5,
    snfPercentage: 9.0,
    farmName: 'Krishna Dairy & Stud Farms',
    milkingTime: '04:00 AM',
    processingTime: '05:45 AM',
    dispatchTime: '07:15 AM',
    image: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?auto=format&fit=crop&q=80&w=600',
    description: 'Rich, thick, and highly nutritious buffalo milk. Great for making homemade thick curd, paneer, and rich kheer.',
    ingredients: 'Pasteurized Homogenized Buffalo Milk',
    nutrition: {
      calories: '97 kcal',
      protein: '3.6g',
      fat: '6.5g',
      carbs: '5.2g',
      calcium: '180mg'
    },
    shelfLife: '48 Hours from packing',
    storageInstructions: 'Keep refrigerated under 4°C at all times.',
    rating: 4.9,
    reviewsCount: 98,
    isPopular: true,
  },
  {
    id: 'p3',
    name: 'A2 Vedic Desi Cow Milk',
    category: 'A2 Milk',
    price: 52,
    unit: '500 ml',
    stock: 120,
    fatPercentage: 4.2,
    snfPercentage: 8.7,
    farmName: 'AyurVeda Goshala Farms',
    milkingTime: '05:00 AM',
    processingTime: '06:15 AM',
    dispatchTime: '07:30 AM',
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&q=80&w=600',
    description: '100% Pure A2 Beta-Casein certified milk from indigenous Gir cows. Easy to digest, highly gut-friendly.',
    ingredients: 'Pasteurized Single Origin Gir Cow A2 Milk',
    nutrition: {
      calories: '65 kcal',
      protein: '3.4g',
      fat: '4.2g',
      carbs: '4.8g',
      calcium: '125mg'
    },
    shelfLife: '48 Hours from packing',
    storageInstructions: 'Keep refrigerated under 4°C at all times.',
    rating: 4.9,
    reviewsCount: 204,
    isPopular: true,
  },
  {
    id: 'p10',
    name: 'Pure Desi Cow Ghee',
    category: 'Ghee',
    price: 499,
    unit: '500 ml',
    stock: 50,
    fatPercentage: 99.8,
    snfPercentage: 0.1,
    farmName: 'AyurVeda Goshala Farms',
    milkingTime: 'Veda Processed',
    processingTime: 'Bilona Churned',
    dispatchTime: 'Ambient Dispatch',
    image: 'https://images.unsplash.com/photo-1622484211148-71759f633390?auto=format&fit=crop&q=80&w=600',
    description: 'Traditional Vedic Bilona method churned ghee, cooked on brass pots with low heat. Highly aromatic with rich granular texture.',
    ingredients: 'Clarified Cow Milk Fat churned from curd (Makhan)',
    nutrition: {
      calories: '897 kcal',
      protein: '0g',
      fat: '99.8g',
      carbs: '0g',
      calcium: '0mg'
    },
    shelfLife: '12 Months from packing',
    storageInstructions: 'Store in a cool, dry place. Do not refrigerate.',
    rating: 4.9,
    reviewsCount: 340,
    isPopular: true,
  },
  {
    id: 'p5',
    name: 'Fresh Malai Paneer',
    category: 'Paneer',
    price: 90,
    unit: '200g',
    stock: 85,
    fatPercentage: 22.0,
    snfPercentage: 11.5,
    farmName: 'Green Valley Organic Farms',
    milkingTime: '04:30 AM',
    processingTime: '08:00 AM',
    dispatchTime: '10:00 AM',
    image: 'https://images.unsplash.com/photo-1629230104113-17b5e4f207cc?auto=format&fit=crop&q=80&w=600',
    description: 'Soft, melt-in-the-mouth paneer made from fresh farm milk. No starch, no chemical coagulants.',
    ingredients: 'Fresh milk solids, lemon juice curdled',
    nutrition: {
      calories: '289 kcal',
      protein: '18.5g',
      fat: '22.0g',
      carbs: '2.5g',
      calcium: '480mg'
    },
    shelfLife: '7 Days',
    storageInstructions: 'Keep refrigerated; submerge in clean water after opening.',
    rating: 4.7,
    reviewsCount: 75,
  },
  {
    id: 'p6',
    name: 'Thick Farm Curd (Dahi)',
    category: 'Curd',
    price: 45,
    unit: '400g',
    stock: 95,
    fatPercentage: 4.0,
    snfPercentage: 9.5,
    farmName: 'Krishna Dairy & Stud Farms',
    milkingTime: '04:00 AM',
    processingTime: '07:30 AM',
    dispatchTime: '10:00 AM',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=600',
    description: 'Thick, creamy set curd containing live probiotic cultures. Prepared traditionally with rich cow milk.',
    ingredients: 'Pasteurized Milk, Active Lactic Cultures (L. casei, S. thermophilus)',
    nutrition: {
      calories: '63 kcal',
      protein: '3.6g',
      fat: '4.0g',
      carbs: '5.0g',
      calcium: '143mg'
    },
    shelfLife: '10 Days',
    storageInstructions: 'Keep refrigerated under 4°C at all times.',
    rating: 4.6,
    reviewsCount: 112,
  },
  {
    id: 'p7',
    name: 'Artisanal White Table Butter',
    category: 'Butter',
    price: 110,
    unit: '200g',
    stock: 60,
    fatPercentage: 82.0,
    snfPercentage: 1.5,
    farmName: 'Krishna Dairy & Stud Farms',
    milkingTime: 'Daily production',
    processingTime: 'Churned at 8°C',
    dispatchTime: 'Cold Chain',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&q=80&w=600',
    description: 'Fresh light white butter churned from organic cream. Salt-free and perfectly rich for parathas and baking.',
    ingredients: 'Pasteurized Sweet Cream churned from Milk',
    nutrition: {
      calories: '740 kcal',
      protein: '0.8g',
      fat: '82.0g',
      carbs: '0.6g',
      calcium: '24mg'
    },
    shelfLife: '30 Days',
    storageInstructions: 'Keep frozen or refrigerated below 2°C.',
    rating: 4.8,
    reviewsCount: 64,
  },
  {
    id: 'p8',
    name: 'Creamy Vanilla Dream Ice Cream',
    category: 'Ice Cream',
    price: 150,
    unit: '500 ml',
    stock: 50,
    fatPercentage: 11.5,
    snfPercentage: 10.0,
    farmName: 'Green Valley Organic Farms',
    milkingTime: 'Processed cold',
    processingTime: 'Blast Frozen',
    dispatchTime: 'Deep Freeze Chain',
    image: 'https://images.unsplash.com/photo-1501443762994-82bd5dace89a?auto=format&fit=crop&q=80&w=600',
    description: 'Premium ice milk solid churned with genuine Bourbon vanilla pods and organic honey. Sweet dairy treat.',
    ingredients: 'Fresh milk, heavy cream, sweet honey, vanilla bean seeds',
    nutrition: {
      calories: '207 kcal',
      protein: '4.2g',
      fat: '11.5g',
      carbs: '22g',
      calcium: '115mg'
    },
    shelfLife: '3 Months',
    storageInstructions: 'Keep frozen below -18°C.',
    rating: 4.8,
    reviewsCount: 89,
  },
  {
    id: 'p9',
    name: 'Gourmet Mild Cheddar Cheese',
    category: 'Cheese',
    price: 180,
    unit: '200g',
    stock: 40,
    fatPercentage: 33.1,
    snfPercentage: 25.0,
    farmName: 'Green Valley Organic Farms',
    milkingTime: 'Aged 3 Months',
    processingTime: 'Coagulated',
    dispatchTime: 'Cold Chain',
    image: 'https://images.unsplash.com/photo-1486299267070-83823f5448dd?auto=format&fit=crop&q=80&w=600',
    description: 'Perfect natural Cheddar cheese with a smooth, golden texturing. Rich in vitamins and natural calcium.',
    ingredients: 'Cultured Milk, Salt, Enzymes, Natural beta-carotene color',
    nutrition: {
      calories: '403 kcal',
      protein: '25.0g',
      fat: '33.1g',
      carbs: '1.3g',
      calcium: '721mg'
    },
    shelfLife: '90 Days',
    storageInstructions: 'Keep refrigerated. Wrap securely in parchment paper after opening.',
    rating: 4.5,
    reviewsCount: 45,
  },
  {
    id: 'p11',
    name: 'Sustain-Green Organic Farm Milk',
    category: 'Organic Milk',
    price: 49,
    unit: '500 ml',
    stock: 90,
    fatPercentage: 4.0,
    snfPercentage: 8.8,
    farmName: 'Green Valley Organic Farms',
    milkingTime: '05:00 AM',
    processingTime: '06:30 AM',
    dispatchTime: '07:45 AM',
    image: 'https://images.unsplash.com/photo-1528750991573-da1aa4d12224?auto=format&fit=crop&q=80&w=600',
    description: '100% certified organic whole cow milk pasture-fed. Completely free of antibiotics, growth hormones, and pesticide residue.',
    ingredients: 'Certified Organic Whole Pasteurized Cow Milk',
    nutrition: {
      calories: '64 kcal',
      protein: '3.3g',
      fat: '4.0g',
      carbs: '4.7g',
      calcium: '122mg'
    },
    shelfLife: '48 Hours from packing',
    storageInstructions: 'Keep refrigerated under 4°C.',
    rating: 4.9,
    reviewsCount: 88,
  },
  {
    id: 'p12',
    name: 'Royal Kesar Pista Flavored Milk',
    category: 'Flavored Milk',
    price: 35,
    unit: '200 ml',
    stock: 140,
    fatPercentage: 3.2,
    snfPercentage: 8.5,
    farmName: 'Krishna Dairy & Stud Farms',
    milkingTime: 'Ambient Bottled',
    processingTime: 'Ultra High Temp Solved',
    dispatchTime: 'Insulated Dispatch',
    image: 'https://images.unsplash.com/photo-1571244856341-4f30521127ae?auto=format&fit=crop&q=80&w=600',
    description: 'Rich sterilized creamy drink infused with premium Kashmiri saffron (Kesar) threads and crunchy pistachios. Refreshing energy source.',
    ingredients: 'Double Toned Milk, Sugar, Pistachio Kernels, Saffron Extractive',
    nutrition: {
      calories: '142 kcal',
      protein: '6.4g',
      fat: '4.1g',
      carbs: '20g',
      calcium: '210mg'
    },
    shelfLife: '120 Days from packing',
    storageInstructions: 'Serve chilled. Shake well before drinking.',
    rating: 4.9,
    reviewsCount: 156,
  },
  {
    id: 'p13',
    name: 'Sweet Mango Punjabi Lassi',
    category: 'Lassi',
    price: 30,
    unit: '250 ml',
    stock: 120,
    fatPercentage: 3.5,
    snfPercentage: 8.6,
    farmName: 'Krishna Dairy & Stud Farms',
    milkingTime: 'Daily production',
    processingTime: 'Sweetened Churned',
    dispatchTime: 'Cold Carrier',
    image: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&q=80&w=600',
    description: 'Authentic rich Punjabi style lassi blended with fresh Alphonso mango pulp and curd. High-calcium coolant.',
    ingredients: 'Fresh Curd, Alphonso Mango Pulp, Sugar, Rose Water traces',
    nutrition: {
      calories: '180 kcal',
      protein: '4.8g',
      fat: '3.5g',
      carbs: '32g',
      calcium: '150mg'
    },
    shelfLife: '7 Days',
    storageInstructions: 'Refrigerate under 4°C. Consume post opening.',
    rating: 4.7,
    reviewsCount: 94,
  },
  {
    id: 'p14',
    name: 'Salted Masala Chaas Buttermilk',
    category: 'Buttermilk',
    price: 20,
    unit: '250 ml',
    stock: 200,
    fatPercentage: 1.5,
    snfPercentage: 8.0,
    farmName: 'Green Valley Organic Farms',
    milkingTime: 'Daily hydration',
    processingTime: 'Diluted Churned',
    dispatchTime: 'Chilled delivery',
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&q=80&w=600',
    description: 'Refreshing spiced low-fat dairy coolant churned with rock salt, natural mint leaf extracts, roasted cumin, and black pepper.',
    ingredients: 'Churned Milk Solids, Water, Edible Salt, Spices (Cumin, Ginger, Mint)',
    nutrition: {
      calories: '38 kcal',
      protein: '1.8g',
      fat: '1.5g',
      carbs: '4.2g',
      calcium: '900mg'
    },
    shelfLife: '5 Days',
    storageInstructions: 'Keep chilled. Best served straight from refrigerator.',
    rating: 4.8,
    reviewsCount: 180,
  },
  {
    id: 'p15',
    name: 'Traditional Bengali Milk Rasgulla Tin',
    category: 'Sweets',
    price: 180,
    unit: '500g',
    stock: 65,
    fatPercentage: 6.8,
    snfPercentage: 12.0,
    farmName: 'AyurVeda Goshala Farms',
    milkingTime: 'Weekly packed',
    processingTime: 'Sugar Concentrated',
    dispatchTime: 'Ambient Courier',
    image: 'https://images.unsplash.com/photo-1589119908995-c6800faecf39?auto=format&fit=crop&q=80&w=600',
    description: 'Soft, spongy cheese balls (Chhena) cooked in simple, clean rose-scented hot sugar syrup. Traditional Bengali recipe.',
    ingredients: 'Sugar syrup, Milk Cottage Cheese (Chhena), Cardamom',
    nutrition: {
      calories: '268 kcal',
      protein: '5.2g',
      fat: '6.8g',
      carbs: '46g',
      calcium: '95mg'
    },
    shelfLife: '6 Months',
    storageInstructions: 'Store in a cool dry space. Consume immediately once seal is broken.',
    rating: 4.9,
    reviewsCount: 110,
    isPopular: true,
  },
  {
    id: 'p16',
    name: 'Greek Blueberry Probiotic Yogurt',
    category: 'Yogurt',
    price: 60,
    unit: '150g',
    stock: 140,
    fatPercentage: 5.0,
    snfPercentage: 11.0,
    farmName: 'Green Valley Organic Farms',
    milkingTime: 'Processed daily',
    processingTime: 'Strained Concentrated',
    dispatchTime: 'Cold Fleet',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&q=80&w=600',
    description: 'Thick, creamy strained Greek yogurt layered with wild blueberry fruit jam. Packed with double protein and gut-friendly probiotics.',
    ingredients: 'Strained Pasteurised Milk, Wild Blueberry Pieces, L. Acidophilus Culture',
    nutrition: {
      calories: '112 kcal',
      protein: '9.5g',
      fat: '4.8g',
      carbs: '13.5g',
      calcium: '160mg'
    },
    shelfLife: '14 Days',
    storageInstructions: 'Store strictly inside refrigerator under 4°C.',
    rating: 4.7,
    reviewsCount: 134,
  },
  {
    id: 'p17',
    name: 'Skimmed Spray Dried Milk Powder',
    category: 'Milk Powder',
    price: 320,
    unit: '1 kg',
    stock: 45,
    fatPercentage: 1.2,
    snfPercentage: 96.0,
    farmName: 'Krishna Dairy & Stud Farms',
    milkingTime: 'Spray Churned',
    processingTime: 'Thermal Evapourated',
    dispatchTime: 'Moisture Safe Fleet',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=600',
    description: 'Standard grade commercial skimmed milk powder with instant-dissolving texture. Perfect for high-yield tea shops and bakeries.',
    ingredients: 'Concentrated Skimmed Raw Cow Milk Spray Dried',
    nutrition: {
      calories: '357 kcal',
      protein: '34g',
      fat: '1.2g',
      carbs: '52g',
      calcium: '1150mg'
    },
    shelfLife: '12 Months',
    storageInstructions: 'Store inside an airtight canister in ambient dry cupboard.',
    rating: 4.6,
    reviewsCount: 52,
  },
  {
    id: 'p18',
    name: 'Ayurvedic Golden Turmeric Milk Drink',
    category: 'Dairy Beverages',
    price: 45,
    unit: '200 ml',
    stock: 130,
    fatPercentage: 3.5,
    snfPercentage: 8.5,
    farmName: 'AyurVeda Goshala Farms',
    milkingTime: 'Herbal Infused',
    processingTime: 'UHT aseptic bottling',
    dispatchTime: 'Direct insulated',
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?auto=format&fit=crop&q=80&w=600',
    description: 'Soothing immunity-boosting milk drink rich in high-potency curcumin extracts, organic black pepper, ginger, and sweet honey.',
    ingredients: 'Double Toned Cow Milk, Honey, Curcumin Sourced Turmeric, Cardamom',
    nutrition: {
      calories: '110 kcal',
      protein: '6.0g',
      fat: '3.4g',
      carbs: '14g',
      calcium: '205mg'
    },
    shelfLife: '60 Days',
    storageInstructions: 'Serve warm or ice chilled for best refreshing state.',
    rating: 4.9,
    reviewsCount: 112,
  },
  {
    id: 'p19',
    name: 'Pure Raw Unpasteurized Forest Honey',
    category: 'Organic Products',
    price: 240,
    unit: '250g',
    stock: 50,
    fatPercentage: 0.0,
    snfPercentage: 0.0,
    farmName: 'Green Valley Organic Farms',
    milkingTime: 'Floral Extracted',
    processingTime: 'Filter Pressed',
    dispatchTime: 'Glass Jar Dispatch',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&q=80&w=600',
    description: 'Raw, unheated, single-origin multi-floral honey filtered through cotton. Rich in vitamins, biological enzymes, and floral pollen.',
    ingredients: '100% Pure Raw Wild Bee honey extract',
    nutrition: {
      calories: '304 kcal',
      protein: '0.3g',
      fat: '0g',
      carbs: '82g',
      calcium: '6mg'
    },
    shelfLife: '24 Months',
    storageInstructions: 'Keep in glass jar at ambient room temperature. Do not refrigerate.',
    rating: 5.0,
    reviewsCount: 164,
  },
  {
    id: 'p20',
    name: 'DairyFresh Standard Toned Milk',
    category: 'Milk',
    price: 28,
    unit: '500 ml',
    stock: 350,
    fatPercentage: 3.0,
    snfPercentage: 8.5,
    farmName: 'Green Valley Organic Farms',
    milkingTime: '04:30 AM',
    processingTime: '06:00 AM',
    dispatchTime: '07:15 AM',
    image: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?auto=format&fit=crop&q=80&w=600',
    description: 'Perfect daily use standardized toned cow milk. Nutritious, budget-friendly choice for tea and home desserts.',
    ingredients: 'Standard Pasteurised Toned Cow Milk',
    nutrition: {
      calories: '58 kcal',
      protein: '3.1g',
      fat: '3.0g',
      carbs: '4.6g',
      calcium: '115mg'
    },
    shelfLife: '48 Hours from packing',
    storageInstructions: 'Refrigerate under 4°C.',
    rating: 4.7,
    reviewsCount: 220,
  }
];

export const INITIAL_DELIVERY_PARTNERS: DeliveryPartner[] = [
  {
    id: 'dp1',
    name: 'Ramesh Kumar',
    phone: '+91 98765 00123',
    status: 'online',
    vehicleType: 'Two Wheeler (Motorcycle)',
    plateNumber: 'KA-03-EX-1290',
    isKycVerified: true,
    totalTrips: 124,
    earnings: 4950,
    penalties: 0,
    aadhaarNumber: 'XXXX-XXXX-4512',
    licenseNumber: 'KA0320210087123',
  },
  {
    id: 'dp2',
    name: 'Suresh Patil',
    phone: '+91 99887 23412',
    status: 'online',
    vehicleType: 'EV Three Wheeler (Chilled Box)',
    plateNumber: 'KA-05-EV-5541',
    isKycVerified: true,
    totalTrips: 89,
    earnings: 3820,
    penalties: 50,
    aadhaarNumber: 'XXXX-XXXX-8921',
    licenseNumber: 'KA0520200055432',
  },
  {
    id: 'dp3',
    name: 'Amit Sharma',
    phone: '+91 96541 78901',
    status: 'offline',
    vehicleType: 'Two Wheeler (Electric)',
    plateNumber: 'KA-01-EL-9902',
    isKycVerified: false,
    totalTrips: 0,
    earnings: 0,
    penalties: 0,
    aadhaarNumber: 'XXXX-XXXX-1104',
    licenseNumber: 'DL0420220199042',
  }
];

export const INITIAL_COLD_STORAGE_UNITS: ColdStorageUnit[] = [
  {
    id: 'cs1',
    name: 'Central Dairy Silo A',
    requiresTemp: '1.5°C to 4.0°C',
    currentTemp: 3.4,
    alertStatus: 'normal',
    capacity: 5000,
    activeBatches: [
      {
        batchNumber: 'BATCH-2026-0602A',
        productName: 'Cow Milk - Pasteurized',
        quantity: '1,200 Litres',
        productionDate: '02 Jun 2026',
        expiryDate: '04 Jun 2026',
        labReportStatus: 'approved',
      },
      {
        batchNumber: 'BATCH-2026-0602B',
        productName: 'Buffalo Milk - Homogenized',
        quantity: '800 Litres',
        productionDate: '02 Jun 2026',
        expiryDate: '04 Jun 2026',
        labReportStatus: 'approved',
      }
    ]
  },
  {
    id: 'cs2',
    name: 'Deep Freeze - Cold Hub 2',
    requiresTemp: '-20.0°C to -15.0°C',
    currentTemp: -18.2,
    alertStatus: 'normal',
    capacity: 2000,
    activeBatches: [
      {
        batchNumber: 'BATCH-ICE-9912',
        productName: 'Vanilla Dream Ice Cream (500ml)',
        quantity: '400 Units',
        productionDate: '30 May 2026',
        expiryDate: '30 Aug 2026',
        labReportStatus: 'approved',
      }
    ]
  },
  {
    id: 'cs3',
    name: 'Cheese Cellar B',
    requiresTemp: '4.0°C to 8.0°C',
    currentTemp: 9.1, // trigger warning!
    alertStatus: 'warning',
    capacity: 1500,
    activeBatches: [
      {
        batchNumber: 'BATCH-CHS-5531',
        productName: 'Mild Cheddar Cheese',
        quantity: '250 kg',
        productionDate: '15 Mar 2026',
        expiryDate: '15 Sep 2026',
        labReportStatus: 'approved',
      }
    ]
  }
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 't1',
    customerId: 'cust_01',
    customerName: 'Rohit Deshmukh',
    complaintType: 'late_delivery',
    message: 'Milk is usually delivered by 7 AM, but today it is already 7:45 AM and I still have not received my daily subscription milk paket! Please assist.',
    status: 'open',
    date: '2026-06-02',
    chatId: 'chat_rohit',
    messages: [
      { sender: 'customer', text: 'My daily milk subscription was scheduled for 7 AM delivery but it has not arrived.', timestamp: '07:40 AM' },
      { sender: 'support', text: 'Apologies for the delay Rohit, our delivery vehicle for Zone A had a minor tyre issue. A replacement agent has picked it up.', timestamp: '07:44 AM' },
      { sender: 'customer', text: 'Okay, when will he reach? My family needs to prepare morning coffee.', timestamp: '07:46 AM' }
    ]
  },
  {
    id: 't2',
    customerId: 'cust_02',
    customerName: 'Sneha Reddy',
    complaintType: 'product_quality',
    message: 'The paneer packet I bought yesterday felt slightly sour. Can I get a replacement or refund?',
    status: 'resolved',
    date: '2026-06-01',
    chatId: 'chat_sneha',
    messages: [
      { sender: 'customer', text: 'The paneer packet was sour.', timestamp: '05:30 PM' },
      { sender: 'support', text: 'We apologize. That is highly unusual as our paneer is cold chain monitored. We have issued a refund of ₹90 back to your Dairy Wallet.', timestamp: '05:45 PM' },
      { sender: 'customer', text: 'Thank you, received the wallet cashback. Excellent customer support response!', timestamp: '05:52 PM' }
    ]
  }
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_101',
    customerId: 'cust_user',
    customerName: 'Anjali Sharma (You)',
    customerAddress: 'Apt 402, Oakwood Residency, Sector 56, Gurgaon',
    phone: '+91 98112 34455',
    items: [
      { product: INITIAL_PRODUCTS[0], quantity: 2 }, // Cow milk
      { product: INITIAL_PRODUCTS[4], quantity: 1 }  // Paneer
    ],
    total: 156, // 33*2 + 90
    status: 'delivered',
    paymentMethod: 'wallet',
    paymentStatus: 'paid',
    deliveryOption: 'instant',
    date: '2026-06-01',
    deliveryPartnerId: 'dp1',
    pickupOtp: '4922',
    deliveryOtp: '7108',
    feedbackRating: 5,
    feedbackReview: 'Extremely fresh and creamy paneer. Delivered in under 30 minutes in a safe insulated thermal bag!',
    milkingDetails: {
      farmName: 'Green Valley Organic Farms',
      milkingTime: '04:30 AM',
      processingTime: '06:00 AM',
      dispatchTime: '07:15 AM',
      deliveryTime: '07:42 AM',
      fatPercent: 3.9,
      snfPercent: 8.6
    }
  },
  {
    id: 'ord_102',
    customerId: 'cust_03',
    customerName: 'Vikram Malhotra',
    customerAddress: 'Villas No 12, Sobha Greenlands, Bangalore',
    phone: '+91 97722 00441',
    items: [
      { product: INITIAL_PRODUCTS[2], quantity: 1 }, // A2 Milk
      { product: INITIAL_PRODUCTS[3], quantity: 1 }  // Cow Ghee
    ],
    total: 551, // 52 + 499
    status: 'ready_pickup',
    paymentMethod: 'upi',
    paymentStatus: 'paid',
    deliveryOption: 'scheduled',
    scheduledTime: '06:00 AM - 08:00 AM, June 03',
    date: '2026-06-02',
    deliveryPartnerId: 'dp2',
    pickupOtp: '8834',
    deliveryOtp: '1902',
    milkingDetails: {
      farmName: 'AyurVeda Goshala Farms',
      milkingTime: '05:00 AM',
      processingTime: '06:15 AM',
      dispatchTime: '07:30 AM',
      fatPercent: 4.25,
      snfPercent: 8.7
    }
  }
];
